"""
Worker layer data models
task_jobs table: records the lifecycle of all async tasks.
Uses a dedicated Base instead of the data_service Base.
"""
import enum
from datetime import datetime, timezone

from sqlalchemy import (
    Column, String, Integer, DateTime, JSON, Text, Enum as SAEnum, Index,
)
from sqlalchemy.orm import declarative_base

# Independent Base to avoid Worker accidentally triggering data_service table creation.
Base = declarative_base()


class TaskStatus(str, enum.Enum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    RETRYING = "retrying"
    REVOKED = "revoked"


class TaskType(str, enum.Enum):
    # preprocess
    BUILD_PYRAMID = "build_pyramid"
    REPROJECT = "reproject"
    COMPUTE_STATS = "compute_stats"
    CONVERT_COG = "convert_cog"
    # index calculation
    CALC_INDEX = "calc_index"
    CALC_CUSTOM = "calc_custom"
    # extraction
    EXTRACT_FEATURE = "extract_feature"
    # clip
    CLIP_RASTER = "clip_raster"
    # export
    EXPORT_GEOJSON = "export_geojson"
    EXPORT_COCO = "export_coco"
    EXPORT_TFRECORD = "export_tfrecord"


class TaskJob(Base):
    """
    async task record table
    job_id      : generated by business logic UUID,frontend uses this ID polling
    celery_task_id : Celery internal task_id,used for revoke
    """
    __tablename__ = "task_jobs"
    __table_args__ = (
        Index("ix_task_jobs_index_id",  "raster_index_id"),
        Index("ix_task_jobs_status",    "status"),
        Index("ix_task_jobs_created_at","created_at"),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    job_id = Column(String(64),  unique=True, nullable=False, index=True)
    celery_task_id = Column(String(64),  nullable=True)

    task_type = Column(String(64),  nullable=False)   # TaskType value
    status = Column(String(16),  nullable=False,
                            default=TaskStatus.PENDING.value)

    # related raster(can be empty,export tasks may not relate to a single raster)
    raster_index_id = Column(String(32), nullable=True)

    # task input snapshot(helps troubleshooting)
    params = Column(JSON,  nullable=True)

    # result metadata(such as generated file index_id,path)
    result = Column(JSON,  nullable=True)

    # error message
    error = Column(Text,  nullable=True)

    # retry count
    retry_count = Column(Integer, default=0)

    # timestamps
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    started_at = Column(DateTime(timezone=True), nullable=True)
    finished_at = Column(DateTime(timezone=True), nullable=True)
