"""layer_fields

Revision ID: 273328c5f494
Revises: 6ded443dd091
Create Date: 2026-03-19 10:29:03.215682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '273328c5f494'
down_revision: Union[str, Sequence[str], None] = '6ded443dd091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('layer_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('layer_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('field_alias', sa.String(), nullable=True),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('field_order', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('default_val', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['layers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('layer_fields', schema=None) as batch_op:
        batch_op.create_index('ix_layer_fields_layer_id', ['layer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layer_fields', schema=None) as batch_op:
        batch_op.drop_index('ix_layer_fields_layer_id')

    op.drop_table('layer_fields')
    # ### end Alembic commands ###
