"""initial_schema

Revision ID: 6ded443dd091
Revises: 
Create Date: 2026-03-05 19:41:10.284936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ded443dd091'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_created_at'), ['created_at'], unique=False)

    op.create_table('layers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_raster_index_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('layers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_layers_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_layers_source_raster_index_id'), ['source_raster_index_id'], unique=False)

    op.create_table('features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('layer_id', sa.UUID(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['layers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index('idx_features_geom', ['geom'], unique=False, postgresql_using='gist')
        batch_op.create_index('idx_features_properties_gin', ['properties'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_layer_category', ['layer_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_features_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_features_layer_id'), ['layer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_layer_id'))
        batch_op.drop_index(batch_op.f('ix_features_category'))
        batch_op.drop_index('idx_layer_category')
        batch_op.drop_index('idx_features_properties_gin', postgresql_using='gin')
        batch_op.drop_index('idx_features_geom', postgresql_using='gist')

    op.drop_table('features')
    with op.batch_alter_table('layers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_layers_source_raster_index_id'))
        batch_op.drop_index(batch_op.f('ix_layers_project_id'))

    op.drop_table('layers')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_created_at'))

    op.drop_table('projects')
    # ### end Alembic commands ###
