"""add_bounds_wgs84_to_rasters

Revision ID: 44e5a475e0a1
Revises: e5f6529cfe37
Create Date: 2026-03-31 15:04:10.250396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e5a475e0a1'
down_revision: Union[str, None] = 'e5f6529cfe37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raster_metadata', sa.Column('bounds_wgs84', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raster_metadata', 'bounds_wgs84')
    # ### end Alembic commands ###
