"""init schema

Revision ID: e5f6529cfe37
Revises: 41d2c53a8915
Create Date: 2026-02-08 16:16:43.586917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f6529cfe37'
down_revision: Union[str, None] = '41d2c53a8915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raster_metadata', sa.Column('index_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_raster_metadata_index_id'), 'raster_metadata', ['index_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raster_metadata_index_id'), table_name='raster_metadata')
    op.drop_column('raster_metadata', 'index_id')
    # ### end Alembic commands ###
